version: "3"
services:
  newsoftware-loja:
    container_name: newsoftware-loja
    image: newsoftware-loja:develop
    ports:
      - "3004:3001"
    build:
      context: .
    volumes:
      - .:/app
    networks:
      - newsoftware
    environment:
      - PORT=3001
      - MONGODB_URL=mongodb://newsoftware-loja-db:27017/loja
      - SECRET_OR_PRIVATE_KEY=c3c7e94f1a9871fcacfd444b7cac5430331ed9ef

  newsoftware-loja-db:
    container_name: newsoftware-loja-db
    image: mongo
    volumes:
      - newsoftware-loja-db:/data/db
    networks:
      - newsoftware

volumes:
  newsoftware-loja-db:

networks:
  newsoftware:
    driver: bridge
